# Generated by Django 5.2.17 on 2026-08-31 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_livraison', models.CharField(max_length=255, verbose_name='Adresse de livraison')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de paiement'), ('confirmee', 'Confirmée'), ('en_livraison', 'En cours de livraison'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('delai_estime_heures', models.PositiveIntegerField(default=24, verbose_name='Délai estimé (heures)')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to=settings.AUTH_USER_MODEL)),
                ('point_distribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.pointdistribution')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=0, max_digits=10)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='commandes.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.produitgaz')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('methode', models.CharField(choices=[('orange_money', 'Orange Money'), ('mtn_momo', 'MTN Mobile Money'), ('especes', 'Espèces à la livraison')], max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('echoue', 'Échoué')], default='en_attente', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=50, verbose_name='Référence de transaction')),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='commandes.commande')),
            ],
        ),
    ]
