# Generated by Django 5.2.17 on 2026-09-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='numero_telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Numéro Mobile Money'),
        ),
    ]
