# Generated by Django 5.2.17 on 2026-09-10 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_paiement_numero_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='mode_livraison',
            field=models.CharField(choices=[('livraison', 'Livraison à domicile'), ('retrait', "Retrait à l'entrepôt")], default='livraison', max_length=20, verbose_name='Mode de récupération'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='adresse_livraison',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresse de livraison'),
        ),
    ]
