# Generated by Django 5.2.17 on 2026-09-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0003_commande_mode_livraison_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='date_annulation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='frais_livraison',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='Frais de livraison (FCFA)'),
        ),
        migrations.AddField(
            model_name='commande',
            name='latitude_client',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='longitude_client',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='motif_annulation',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
