# Generated by Django 5.2.17 on 2026-09-25 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0004_commande_date_annulation_commande_frais_livraison_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='montant_rembourse',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='politique_acceptee',
            field=models.BooleanField(default=False, verbose_name="Politique d'annulation acceptée"),
        ),
        migrations.AddField(
            model_name='commande',
            name='taux_remboursement',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Taux de remboursement (%)'),
        ),
    ]
