# Generated by Django 5.2.17 on 2026-08-31 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('quartier', models.CharField(blank=True, max_length=100, verbose_name='Quartier')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Point de distribution',
                'verbose_name_plural': 'Points de distribution',
            },
        ),
        migrations.CreateModel(
            name='ProduitGaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('poids_kg', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Poids (kg)')),
                ('prix', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Prix (FCFA)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('stock_disponible', models.PositiveIntegerField(default=0, verbose_name='Stock disponible')),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/', verbose_name='Image')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif (visible sur le site)')),
            ],
            options={
                'verbose_name': 'Produit de gaz',
                'verbose_name_plural': 'Produits de gaz',
            },
        ),
    ]
