# Generated by Django 5.2.17 on 2026-09-10 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livraison',
            old_name='date_prise_en_charge',
            new_name='date_assignation',
        ),
        migrations.AddField(
            model_name='livraison',
            name='date_acceptation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livraison',
            name='position_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='livraison',
            name='position_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='livraison',
            name='position_maj_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='statut',
            field=models.CharField(choices=[('en_attente', "En attente d'attribution"), ('assignee', "Assignée, en attente d'acceptation"), ('en_cours', 'En cours de livraison'), ('livree', 'Livrée')], default='en_attente', max_length=20),
        ),
    ]
