# Generated by Django 5.2.17 on 2026-09-10 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0002_rename_date_prise_en_charge_livraison_date_assignation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livraison',
            name='position_maj_le',
        ),
        migrations.AddField(
            model_name='livraison',
            name='position_precision',
            field=models.FloatField(blank=True, help_text='Précision GPS en mètres', null=True),
        ),
    ]
