# Generated by Django 5.2.17 on 2026-09-25 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0003_remove_livraison_position_maj_le_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='statut',
            field=models.CharField(choices=[('en_attente', "En attente d'attribution"), ('assignee', "Assignée, en attente d'acceptation"), ('en_cours', 'En cours de livraison'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=20),
        ),
    ]
